name: Continuous Integration with Maven

on:
  push:
    branches: [ main ]

env:
  # Application
  APPLICATION_NAME: service-discovery
  # Java
  JAVA_VERSION: 1.11
  # DockerHub
  DOCKER_HUB_USERNAME: michaelxsteinertxcontainer

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Messaging Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: 'Continuous Integration for ServiceDiscovery ongoing'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
        
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Maven Clean Package and Push to Dockerhub
        run: ./mvnw clean package -P build-and-push-container-to-dockerhub

      - name: Messaging Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: 'Pushed ${{env.APPLICATION_NAME}} to DockerHub'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}